global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'service-one'
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'service-two'
    static_configs:
      - targets: ['host.docker.internal:8082']